### ISSUE TITLE
Spec: iOS SDK

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/ios-sdk#1]
@pranavrajs commented on [Thu Sep 02 2021](https://github.com/chatwoot/product/issues/201)

**Todo:** 

- [ ] List of APIs and their documents to be shared with Shamsu. (@sojan-official)
- [ ] Design mocks/wireframes for him to work. (@pranavrajs)
- [ ] Account on staging to test and work on the APIs
- [ ] Create a list of tasks/milestones for the task
- [ ] Spec out the functions and input for SDK.

---

@pranavrajs commented on [Fri Sep 03 2021](https://github.com/chatwoot/product/issues/201#issuecomment-911982755)

- Native SDK for iOS should support all the features supported by the web-widget. The expected features for the SDK are as follows:
    - **Initialization:** Allow users to initialize the SDK with a Host, an inbox identifier, language.
    - **Conversations:** Allow the users to support more that one conversation in the widget and respond to them simultaneously. 
        - Once a conversation is resolved, based on the configuration, the conversation may or may not be reopened.
        - Notify the user on new messages if the app is closed/minimized.
        - Provide a notification badge option to display how many unread messages are available.
        - **Message Types:** (Upload and render)
            - **V1**:
                - Text - Should support markdown
                - Image
                - Audio
                - File
                - If none of these, use a fallback that the message type is not supported.
            - **V2:**
                - Options message
                - Form message
                - Input box
                - Card message
                - Article Message
                - CSAT Message
    - **Contact**:
        - There are 3 types of contacts: Anonymous, Users set by SDK, Users authenticated by identity validation.
            - `setUser` method which accepts the user attributes along with the identifier.
        - Allow adding tags to the contact. `setContactLabel` method should be exposed.
        - Allow adding custom attributes to the contact using `setCustomAttributes` method.
    - Display "Powered by Chatwoot" at the bottom.
    - Support i18n as we have it in web widget.
- **Open questions:**
    - Do we need to support business hours?
    - Do we need to support pre-chat form?
    - Do we need to support email collect box?

---

@pranavrajs commented on [Fri Sep 03 2021](https://github.com/chatwoot/product/issues/201#issuecomment-911995839)

|list|conversation|
|--|--|
|<img width="375" alt="list screen" src="https://user-images.githubusercontent.com/2246121/131905443-c996d5e4-0611-4db4-bbac-33a4204b5d10.png">|<img width="375" alt="conversation screen" src="https://user-images.githubusercontent.com/2246121/131905433-4f815b01-d575-4ca0-bcf6-a4999afd218e.png">|

**Comment by sojan-official** [comment]
Let's build the initial implementation over the client APIs available for the API channel.
ref: https://www.chatwoot.com/docs/product/channels/api/client-apis
https://www.chatwoot.com/developers/api/#tag/Contacts-API
